name: Initialize Google Sheet

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y gcc python3-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.19.5
        pip install pandas==1.2.4
        pip install openpyxl
        pip install -r requirements.txt
    
    - name: Initialize sheet
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
      run: python init_google_sheet.py 