name: Send Traffic Update Message

on:
  workflow_dispatch:  # Возможность запуска вручную

jobs:
  send-message:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip cache purge
        pip uninstall -y numpy pandas openpyxl || true
        python -m pip install --force-reinstall --no-cache-dir numpy==1.24.3
        python -m pip install --force-reinstall --no-cache-dir pandas==2.0.3
        python -m pip install --no-cache-dir -r requirements.txt
    
    - name: Send message to working chat
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        AHREFS_API_KEY: ${{ secrets.AHREFS_API_KEY }}
      run: python send_update_message.py 