name: Send Real Data to Test Chat

on:
  workflow_dispatch:  # Возможность запуска вручную

jobs:
  send-test-message:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements.txt
    
    - name: Send real data message to test chat only
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        AHREFS_API_KEY: ${{ secrets.AHREFS_API_KEY }}
      run: python show_full_message.py 