name: Test Telegram

on:
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip cache purge
        pip uninstall -y numpy pandas openpyxl || true
        python -m pip install --force-reinstall --no-cache-dir numpy==1.24.3
        python -m pip install --force-reinstall --no-cache-dir pandas==2.0.3
        python -m pip install --no-cache-dir -r requirements.txt
    
    - name: Run Telegram test
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: python test_telegram.py 