name: Traffic Monitor

on:
  schedule:
    - cron: '0 10 * * 1'  # Каждый понедельник в 10:00 GMT+2
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install pandas=1.5.3 -y
        pip install -r requirements.txt
    
    - name: Run monitor
      shell: bash -l {0}
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
      run: python run_test.py 